[package]
name = "srcapi-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
reqwest = "0.11.12"
serde = { version = "1.0.85", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.1", features = ["full"] }
